#pragma once
#include "Utils.h"

class CarPhysicsState {
public:
	unsigned char physicsGUID;
	mat44f worldMatrix;
	mat44f suspensionMatrix[4];
	mat44f tyreMatrix[4];
	float engineRPM;
	bool isEngineLimiterOn;
	float wheelAngularSpeed[4];
	float steer;
	float gas;
	float brake;
	float clutch;
	int gear;
	Speed speed;
	vec3f velocity;
	vec3f localVelocity;
	vec3f localAngularVelocity;
	vec3f angularVelocity;
	float slipAngle[4];
	float slipRatio[4];
	float tyreSlip[4];
	float ndSlip[4];
	float load[4];
	float Dy[4];
	float Mz[4];
	float tyreDirtyLevel[4];
	SurfaceDef tyreSurfaceDef[4];
	float cgHeight;
	vec3f accG;
	unsigned int lapTime;
	unsigned int lastLap;
	unsigned int bestLap;
	unsigned int lapCount;
	float lastFF_Pure;
	float lastFF_Final;
	SCarStateAero aero;
	vec3f tyreContactPoint[4];
	vec3f tyreContactNormal[4];
	float camberRAD[4];
	float tyreRadius[4];
	float tyreLoadedRadius[4];
	float suspensionTravel[4];
	float normalizedSplinePosition;
	float driftPoints;
	float instantDrift;
	bool isDriftValid;
	int driftComboCounter;
	bool driftBonusOn;
	float drivetrainSpeed;
	float turboBoost;
	float performanceMeter;
	float performanceMeterSpeedDiffMS;
	bool isGearGrinding;
	float bodyWorkVolume;
	float tyreVirtualKM[4];
	float damageZoneLevel[5];
	int limiterRPM;
	plane4f groundPlane;
	double timeStamp;
	float airDensity;
	float fuel;
	float fuelLaps;
	float rideHeight[2];
	bool isRetired;
	float engineLifeLeft;
	float turboBov;
	float turboBoostLevel;
	float tyreGrain[4];
	float tyreBlister[4];
	DriverActionsState actionsState;
	CarSetupState setupState;
	float tyreInflation[4];
	float kersCharge;
	float kersInput;
	float gearRpmWindow;
	float susDamage[4];
	float tyreFlatSpot[4];
	float water;
	TyreThermalState tyreThermalStates[4];
	float discTemps[4];
	float wear[4];
	float wearMult[4];
	float lockControlsTime;
	float kersCurrentKJ;
	bool kersIsCharging;
	unsigned int statusBytes;
	unsigned char p2pStatus;
	unsigned char p2pActivations;
	float antiSquat;
	float caster[2];
};

